### ISSUE TITLE
Leverage GODOT_BIN_PATH? 

### ISSUE THREAD

**Issue by zetashift** [geekrelief/gdnim#16]
Should we include an option to not set godot's path manually in build.ini, but if there is a GODOT_BIN_PATH use that?
GodotNim uses this environment variable too, so it might lower the entry just a lil' bit.

**Comment by geekrelief** [comment]
I'm not keen on the idea. I could check for the environment variable, but I'd still want the variables in the build.ini to take priority.  So that would mean having a build.ini with those variables removed or commented out assuming someone had GODOT_BIN_PATH set or used godot-nim before.  At that point, I don't think that someone looking at gdnim would consider setting ini values as being an issue. Also, if the user is new to godot-nim, then having the variables in `build.ini` makes things easier to setup without polluting the environment variables.

Plus if you're running multiple versions of the engine (with the voxel or ecs module) you can pass in different configurations easily e.g. `./build --ini:build_with_voxel_module.ini cleanbuild`.  And you can symlink or copy those different configurations to `build.ini` for convenience.

**Comment by zetashift** [comment]
Fair points, the build.ini isn't that much of a big deal, I'll close this!
